account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import UserLoginForm, PwdResetForm, PwdResetConfirmForm

app_name = 'account'

urlpatterns = [
     path('register/', views.account_register, name='register'),
     path('activate/<slug:uidb64>/<slug:token>', views.account_activate, name='activate'),
     
     path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
                                                  form_class=UserLoginForm), name='login'),
     path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
     
     # user details
     path('dashboard/', views.dashboard, name='dashboard'),

     path('profile/edit', views.profile_edit, name='profile_edit'),
     path('profile/delete_user', views.profile_delete, name='profile_delete'),
     path('profile/delete_confirm', TemplateView.as_view(
          template_name='account/dashboard/delete_confirm.html',), name='delete_confirmation'),

     path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/dashboard/password_reset_form.html",
                                                                      success_url='password_reset_email_confirm',
                                                                      email_template_name='account/dashboard/password_reset_email.html',
                                                                      form_class=PwdResetForm), name='pwdreset'),
     path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/dashboard/password_reset_confirm.html',
                                                                                                    success_url='password_reset_complete/',
                                                                                                    form_class=PwdResetConfirmForm),
          name="password_reset_confirm"),
     path('password_reset/password_reset_email_confirm/',
          TemplateView.as_view(template_name="account/dashboard/reset_status.html"), name='password_reset_done'),
     path('password_reset_confirm/NQ/password_reset_complete/',
         TemplateView.as_view(template_name="account/dashboard/reset_status.html"), name='password_reset_complete'),
     
     # wishlist
     path('wishlist/', views.wishlist, name='wishlist'), 
     path('wishlist/add/<int:id>', views.add_wishlist, name='add_wishlist'), 
]

basket/urls.py
from django.urls import  path


from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary,  name='basket_summary'),   
    path('add/', views.basket_add,  name='basket_add'), 
    path('delete/', views.basket_delete,  name='basket_delete'),
    path('update/', views.basket_update,  name='basket_update'), 
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='index'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}" >
    <link rel="stylesheet" href="{% static 'basket/css/basket.css' %}" >
    </head>

<body>
    <header class="pb-3">
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid px-md-4">
                <div class="d-flex w-100 navbar-collapse">
                    <a class="navbar-brand d-flex-inline" href="/">
                        <i class="fa-solid fa-bitcoin-sign"></i>
                    </a>
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle d-none d-md-block fw500" href="#" id="navbarDropdown"
                                role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Library
                                <i class="fa-solid fa-chevron-down"></i>
                            </a>
                            <ul class="dropdown-menu rounded-0 border-0" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "store:index" %}">All</a></li>
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <div>
                            <i class="fa-solid fa-list"></i>
                        </div>
                        <span class="fs15 fw500">Shop</span>
                    </button>

                    {% if user.is_authenticated %}
                    <a type="button" role="button" href="{%url "account:logout"%}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <i class="fa-solid fa-door-closed"></i>
                        </div>
                        <span class="fs15 fw500">Logout</span>
                    </a>
                    {% else %}
                    <a type="button" role="button" href="{%url "account:login"%}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <i class="fa-solid fa-door-closed"></i>
                        </div>
                        <span class="fs15 fw500">Login</span>
                    </a>
                    {% endif %}


                    <a type="button" role="button" href="{%url "account:dashboard"%}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <i class="fa-solid fa-user"></i>
                        </div>
                        <span class="fs15 fw500">Account</span>
                    </a>

                    <a type="button" role="button" href="{%url "account:wishlist"%}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <i class="fa-solid fa-list-ol"></i>
                        </div>
                        <span class="fs15 fw500">Wishlist</span>
                    </a>

                    <a type="button" role="button" href="{% url "basket:basket_summary" %}"
                        class="btn btn-outline-secondary border-0 basket-btn">

                        {% with total_qty=basket|length %}
                        <div id="basket-qty" class="basket-qty">
                            {% if total_qty > 0 %}
                            {{ total_qty }}
                            {% else %}
                            0
                            {% endif %}
                        </div>
                        {% endwith %}
                        <div>
                            <i class="fa-solid fa-basket-shopping"></i>
                        </div>
                        <span class="fs15 fw500">Basket</span>
                    </a>
                </div>
                <div class="d-md-none d-lg-none d-xl-none">
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li><a class="dropdown-item" href="{% url "store:index" %}">All</a></li>
                            {% for c in categories %}
                            <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <form class="d-flex w-100 d-md-none">
                    <input class="form-control me-2" type="search" placeholder="Search products or FAQ"
                        aria-label="Search">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <main class='pt-5'>
    <div id="content">{% block content %} {% endblock %}</div>
    </main>
    <div class="container">
        <footer class="py-3 my-4">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="{% url 'store:index'%}" class="nav-link px-2 text-muted">Home</a></li>
                <li class="nav-item"><a href="{% url 'store:index'%}" class="nav-link px-2 text-muted">Features</a></li>
                <li class="nav-item"><a href="{% url 'store:index'%}" class="nav-link px-2 text-muted">Pricing</a></li>
                <li class="nav-item"><a href="{% url 'store:index'%}" class="nav-link px-2 text-muted">About</a></li>
            </ul>
            <p class="text-center text-muted">© 2022 Kenzo, Yan</p>
        </footer>
    </div>

</body>

</html>