basket/urls.py
from django.urls import  path


from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary,  name='basket_summary'),   
    path('add/', views.basket_add,  name='basket_add'), 
    path('delete/', views.basket_delete,  name='basket_delete'),
    path('update/', views.basket_update,  name='basket_update'), 
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='index'),
    path('item/<slug:slug>/', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

basket/models.py
from django.db import models

# Create your models here.

basket/views.py
from urllib import response
from django.shortcuts import render ,get_object_or_404

from django.http import JsonResponse

from .basket import Basket
from store.models import Product 
# Create your views here.


def basket_summary(request):
    basket = Basket(request)
    return render(request, "basket/summary.html",{'basket':basket})


def basket_add(request):
    basket =Basket(request)
    if request.POST.get("action") == 'post':
        product_id = int(request.POST.get("product_id"))
        product_qty = int(request.POST.get("product_qty"))
        product = get_object_or_404(Product, id=product_id) 
        basket_qty = basket.__len__()
        basket.add(product=product, product_qty=product_qty)
        response = JsonResponse({'qty':basket_qty})
        return response

def basket_delete(request):
    basket =Basket(request)

    if request.POST.get("action") == 'post':
        product_id = int(request.POST.get("product_id"))
        
        basket.delete(product_id=product_id)
        basketqty = basket.__len__()
        total_price_basket = basket.get_total_price()
        subtotal_price = basket.get_subtotal_price()
        response = JsonResponse({'success':"Deleted" ,'qty':basketqty, 'total': total_price_basket, 'subtotal_price':subtotal_price})
        return response

def basket_update(request):
    basket =Basket(request)
    print(request.POST)
    if request.POST.get("action") == 'post':
        product_id = int(request.POST.get("product_id"))
        product_qty = int(request.POST.get("product_qty"))
        basket.update(product_id=product_id, product_qty=product_qty)

        basketqty = basket.__len__()
        total_price_basket = basket.get_total_price()
        subtotal_price = basket.get_subtotal_price()
        response = JsonResponse({'success':"Updated", 'qty':basketqty, 'total': total_price_basket, 'subtotal_price':subtotal_price})
        return response
    

templates/basket/summary.html
{% extends "../base.html" %}
{% load static %}
{% block title %} Basket Summary {% endblock %}

{% block content %}
  <div class="container" >
    <div class="col-12">
      <h1 class="h2 text-center">Your Basket</h1>
    </div>
    <div class="col-12 text-center" >
      <p>Manage your <b>items</b> in your basket</p>
    </div>
    <hr />
  </div>

  <div class="container">
    
    <div class="row g-3">
      {% if basket|length == 0%}
      <div class="h4 text-center">Your basket is empty </div>
      <div class="h4 text-center">Go <a href="{% url 'store:index' %}">Shopping</a> Now ! </div>
      
      {% else %}
      <div class="col-12 bg-light p-3 d-flex justify-content-between">
        <div class="d-flex d-flex-inline">
          <div class="pe-3">Order</div>
          <div class="dropdown">
          <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" id="dropdownLink" data-bs-toggle="dropdown" aria-expanded="false">
          Shipping options
          <i class="fa-solid fa-chevron-down"></i>
          </a>

          <ul class="dropdown-menu" aria-labelledby="dropdownLink">
            <li class="item small">Next day delivery</li>
            <li class="item small">Premimum delivery</li>
          </ul>
          </div>
        </div>
        <div class="text-end">
          
          <div class="">Sub Total: <span class="fw-bold">€</span><div id="subtotal" class="d-inline-flex fw-bold">{{basket.get_subtotal_price}}</div></div>
          <div >Shipping <span class="small">(Next day delivery)</span>: <span class="fw-bold">€9.99</span></div>
          <div id="basket-qty" >Total Qty: <div id="basket-qty" class="d-inline-flex fw-bold">{{basket|length}}</div></div>

          <div class="pt-2">Total to pay: <span class="fw-bold h5">€</span><span id="total" class="fw-bold h5">{{basket.get_total_price}}</span></div>
          
        </div>
      </div>
      
      <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
        <div class="d-grid gap-2 ">
          <a role="button" href="{% url "payment:basket"%}" class="btn btn-success fw-bold" type="button">Checkout</a>
          <button class="btn btn-light" type="button">Save for later</button>
        </div>
      </div>
      <div class="col-md-7 col-lg-8 p-0">

        {% for item in basket %} 
        {% with product=item.product %}

        <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
          <div class="row g-0">
            <div class="col-md-2 d-none d-md-block">
              <img class="img-fluid mx-auto d-block" alt="Responsive image"
                  src="{{ product.image.url }}" />
            </div>
            <div class="col-md-10 ps-md-3">
              <div class="card-body p-1">
                <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                  <p class="card-text pb-3">{{product.title}}</p>
                </a>
                    <label for="select">Qty</label>
                    <select id="select{{product.id}}" style="width:50px;height:31px;">
                      <option value="" selected disabled hidden>{{item.qty}}</option>
                      <option value="">1</option>
                      <option value="">2</option>
                      <option value="">3</option>
                      <option value="">4</option>
                    </select>
                <a type="button" id="update-button" data-index="{{product.id}}" class="update-button text-decoration-none small ps-3">Update</a>
                <a type="button" id="delete-button" data-index="{{product.id}}" class="delete-button text-decoration-none small">Delete</a>
              </div>
            </div>
          </div>
        </div>
        {% endwith %} 
        {% endfor %}
      </div>
      {% endif %}
    </div>
    
  </div>

<script>
  $(document).on('click', '.delete-button', function (e) {
    e.preventDefault();
    let prodid = $(this).data('index')
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_delete" %}',
      data: {
        product_id: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post',
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();
        document.getElementById('subtotal').innerHTML = json.subtotal_price
        document.getElementById('basket-qty').innerHTML = json.qty
        document.getElementById('total').innerHTML = json.total
      },
      error: function (xhr, errmsg, err) {}
    });
  })

  $(document).on('click', '.update-button', function (e) {
    e.preventDefault();
    let prodid = $(this).data('index')
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_update" %}',
      data: {
        product_id: $(this).data('index'),
        product_qty: $('#select' + prodid + ' option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post',
      },
      success: function (json) {
        document.getElementById('subtotal').innerHTML = json.subtotal_price
        document.getElementById('basket-qty').innerHTML = json.qty // not update ???  //
        document.getElementById('total').innerHTML = json.total
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>

{% endblock %}